{
    jakehamilton = { forum = "jakehamilton"; github = "jakehamilton"; };
    jeff = { forum = "jeff"; github = "jeff-hykin"; };
    axel = { forum = "axel"; github = "axelsilverdew"; };
    isabel = { forum = "isabel"; github = "isabelroses"; };
    imadnyc = { forum = "imadnyc"; github = "imadnyc"; };
    liketechnik = { forum = "liketechnik"; github = "liketechnik"; };
    nova = { forum = "nova"; github = "novamacintyre"; };
    dfh = { forum = "dfh"; github = "dantefromhell"; };
    c8h4 = { forum = "c8h4"; github = "cristoph-heiss"; };
    "8bitbuddhist" = { forum = "8bitbuddhist"; github = "8bitbuddhist"; };
    coded = { forum = "coded"; github = "thecodedprof"; };
    vera = { forum = "vera"; github = "zumorica"; };
    blue = { forum = "blue"; github = "bluelinden"; };
    "0xmrtt" = { forum = "0xmrtt"; github = "0xmrtt"; };
    bbjubjub = { forum = "bbjubjub"; github = "bbjubjub2494"; };
    vlinkz = { forum = "vlinkz"; github = "vlinkz"; };
    sigma = { forum = "sigma"; github = "sigmanificient"; };
    minion = { forum = "minion"; github = "minion3665"; };
    daholli = { forum = "daholli"; github = "daholli"; };
    evanrichter = { forum = "evanrichter"; github = "evanrichter"; };
    marshmallow = { forum = "marshmallow"; github = "mrshmllow"; };
    trespaul = { forum = "trespaul"; github = "trespaul"; };
    greyrat = { forum = "greyrat"; github = "greyratdev"; };
    ptitfred = { forum = "ptitfred"; github = "ptitfred"; };
    jacab = { forum = "jacab"; github = "turkeysanwich"; };
    srxl = { forum = "srxl"; github = "sorixelle"; };
    loggers = { forum = "loggers"; github = "purrpurrn"; };
    gopher = { forum = "gopher"; github = "hedyhli"; };
    nyawox = { forum = "nyawox"; github = "nyawox"; };
    lychee = { forum = "lychee"; github = "itslychee"; };
    licebmi = { forum = "licebmi"; github = "licebmi"; };
    angryant = { forum = "angryant"; github = "angryant"; };
    wamserma = { forum = "wamserma"; github = "wamserma"; };
    psentee = { forum = "psentee"; github = "psentee"; };
    raf = { forum = "raf"; github = "notashelf"; };
    eri = { forum = "eri"; github = "eerii"; };
    codingpuffin = { forum = "codingpuffin"; github = "nulhomme"; };
    eljamm = { forum = "eljamm"; github = "eljamm"; };
    nixfemby = { forum = "nixfemby"; github = "nixfemby"; };
    daylinmorgan = { forum = "daylinmorgan"; github = "daylinmorgan"; };
    federicoschonborn = { forum = "federicoschonborn"; github = "federicoschonborn"; };
    yulian = { forum = "yulian"; github = "yulian"; };
    aria = { forum = "aria"; github = "tcmal"; };
    ircurry = { forum = "ircurry"; };
    aprl = { forum = "aprl"; };
    deivpaukst = { forum = "deivpaukst"; };
    tau = { forum = "tau"; };
    srestegosaurio = { forum = "srestegosaurio"; };
}
